name = ""
license = "MIT"
licenselink = "https://github.com/razonyang/hugo-mod-google-adsense/blob/main/LICENSE"
description = ""
homepage = "https://github.com/razonyang/hugo-mod-google-adsense"
tags = []
features = []
min_version = "0.97.0"

[author]
  name = ""
  homepage = ""
